#pragma once
#include "stdafx.h"

typedef D3DXMATRIXA16 MAT;


typedef D3DXVECTOR2 VEC2;
typedef D3DXVECTOR3 VEC3;
typedef D3DXVECTOR4 VEC4;


typedef D3DXQUATERNION QUAT;
typedef D3DXPLANE	   PLAN;


typedef LPDIRECT3DVERTEXBUFFER9			LPVB;
typedef LPDIRECT3DINDEXBUFFER9			LPIB;
typedef LPD3DXMESH						LPMESH;
typedef LPDIRECT3DTEXTURE9				LPTXUR;
typedef LPDIRECT3DVERTEXSHADER9			LPVS;
typedef LPDIRECT3DVERTEXDECLARATION9	LPVD;


typedef D3DMATERIAL9 DMTL;
typedef D3DLIGHT9	 DLIT;


typedef LPD3DXBUFFER LPBF;
typedef D3DXMATERIAL XMTL;


typedef D3DXIMAGE_INFO DIMG;
